
package Vista;

import Modelo.Cliente;
import Modelo.ClienteDao;
import Modelo.login;
import Reportes.ExcelClientes;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    
    private int idUsuario;
    private String nombreUsuario;
    private login usuario;
    
    public Clientes(login usuario) {
        this.usuario = usuario;
        initComponents();
        cargarClientes();
        initBuscadorClientes();     
        aplicarPlaceholder(txtBuscarClientes, "Buscar");
        this.setLocationRelativeTo(null); 
    }

    
   

    private void cargarClientes() {
    ClienteDao clienteDAO = new ClienteDao();
    List<Cliente> lista = clienteDAO.listarClientesConTicket();

    DefaultTableModel modelo = (DefaultTableModel) TablaClientes.getModel();
    modelo.setRowCount(0);

    for (Cliente c : lista) {
        String textoBoton = (c.getIdTicket() == 0) ? "SIN TICKET" : "VER TICKET";
        modelo.addRow(new Object[]{
            c.getIdCliente(),
            c.getNombre(),
            textoBoton,
            c.getRutaPDF()
        });
    }

    // Ocultar la columna rutaPDF
    TablaClientes.getColumnModel().getColumn(3).setMinWidth(0);
    TablaClientes.getColumnModel().getColumn(3).setMaxWidth(0);
}


    private void manejarClickTablaClientes(java.awt.event.MouseEvent evt) {
    int fila = TablaClientes.rowAtPoint(evt.getPoint());
    int columna = TablaClientes.columnAtPoint(evt.getPoint());

    if (columna == 2) { // Columna Ticket
        String texto = TablaClientes.getValueAt(fila, 2).toString();
        if (texto.equals("SIN TICKET")) {
            JOptionPane.showMessageDialog(this, "Este cliente no tiene ticket.");
            return;
        }

        String rutaPDF = TablaClientes.getValueAt(fila, 3).toString();
        java.io.File pdf = new java.io.File(rutaPDF);

        if (pdf.exists()) {
            try {
                java.awt.Desktop.getDesktop().open(pdf);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "No se pudo abrir el ticket.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "El archivo PDF no fue encontrado.");
        }
    }
}
    
    private void buscarClientes(String criterio) {
    ClienteDao clienteDAO = new ClienteDao();
    List<Cliente> lista = clienteDAO.buscarClientesConTicket(criterio);

    DefaultTableModel modelo = (DefaultTableModel) TablaClientes.getModel();
    modelo.setRowCount(0);

    for (Cliente c : lista) {
        String textoBoton = (c.getIdTicket() == 0) ? "SIN TICKET" : "VER TICKET";
        modelo.addRow(new Object[]{
            c.getIdCliente(),
            c.getNombre(),
            textoBoton,
            c.getRutaPDF()
        });
    }

    // Ocultar columna rutaPDF
    TablaClientes.getColumnModel().getColumn(3).setMinWidth(0);
    TablaClientes.getColumnModel().getColumn(3).setMaxWidth(0);
}

    // Método para inicializar el buscador
    private void initBuscadorClientes() {
    txtBuscarClientes.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            String texto = txtBuscarClientes.getText().trim();
            if (texto.isEmpty()) {
                cargarClientes(); // recarga todos los clientes
            } else {
                buscarClientes(texto); // filtra por id o nombre
            }
        }
    });
}
    
    public static void aplicarPlaceholder(JTextField campo, String placeholder) {
    campo.setText(placeholder);
    campo.setForeground(Color.GRAY);

    campo.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            if (campo.getText().equals(placeholder)) {
                campo.setText("");
                campo.setForeground(Color.BLACK);
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent e) {
            if (campo.getText().isEmpty()) {
                campo.setText(placeholder);
                campo.setForeground(Color.GRAY);
            }
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        txtBuscarClientes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Cliente", "Nombre", "Ticket", "RutaPDF"
            }
        ));
        TablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaClientes);
        if (TablaClientes.getColumnModel().getColumnCount() > 0) {
            TablaClientes.getColumnModel().getColumn(0).setPreferredWidth(60);
            TablaClientes.getColumnModel().getColumn(2).setPreferredWidth(60);
            TablaClientes.getColumnModel().getColumn(3).setPreferredWidth(60);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Clientes");

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/regresar_2.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/excel.png"))); // NOI18N
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtBuscarClientes, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnRegresar)
                            .addGap(59, 59, 59)
                            .addComponent(jLabel1)
                            .addGap(77, 77, 77))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresar)
                    .addComponent(jLabel1))
                .addGap(55, 55, 55)
                .addComponent(txtBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcel)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        System.out.println("Usuario en boton Regresar: " + (usuario != null ? usuario.getNombre() : "null"));
        System.out.println("Rol en boton Regresar: " + (usuario != null ? usuario.getRol() : "null"));
        System.out.println("ID en boton Regresar: " + (usuario != null ? usuario.getId() : "null"));

        if (usuario != null) {
            SistemaPrincipal sp = new SistemaPrincipal(usuario);
            sp.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error: usuario no inicializado.");
        }
    
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void TablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClientesMouseClicked
        // TODO add your handling code here:
        manejarClickTablaClientes(evt);

    }//GEN-LAST:event_TablaClientesMouseClicked

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        ExcelClientes.reporte();
    }//GEN-LAST:event_btnExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Clientes().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaClientes;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarClientes;
    // End of variables declaration//GEN-END:variables
}
