
package Vista;

import Modelo.InventarioDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Modelo.Inventario;
import javax.swing.JOptionPane;

public class Inventarios extends javax.swing.JFrame {

    public static Inventarios instancia;
    private Inventarios inventarioVentana;
    
    public Inventarios() {
        initComponents();
        configurarRenderer();
        listarInventario();
        instancia = this;
        this.setLocationRelativeTo(null);
    }
    


    private Compras comprasPanel; // referencia a Compras
    public void setComprasPanel(Compras compras) {
    this.comprasPanel = compras;
}

    public void refrescarInventario() {
    listarInventario();
}

   public void listarInventario() {
    InventarioDAO dao = new InventarioDAO();
    List<Modelo.Inventario> lista = dao.listar();
    DefaultTableModel modelo = (DefaultTableModel) TablaInventario.getModel();
    modelo.setRowCount(0);

    double totalInventario = 0;   // suma de todo el inventario válido
    double totalRecibido = 0;     // suma solo de los recibidos

    for (Modelo.Inventario i : lista) {
        modelo.addRow(new Object[]{
            i.getIdArticulo(), 
            i.getNombre(), 
            i.getUnidad(),
            i.getCantidadComprada(),
            i.getStockActual(), 
            String.format("%.2f", i.getCostoUnitario()),
            String.format("%.2f", i.getValorInventario()),
 
            i.getEstado()
        });

        // Ignorar cancelados en cálculos
        if (!"Cancelado".equalsIgnoreCase(i.getEstado())) {
            totalInventario += i.getValorInventario();
        }

        if ("Recibido".equalsIgnoreCase(i.getEstado())) {
            totalRecibido += i.getValorInventario();
        }
//        
//        // ALERTA: stock bajo
//    if (i.getStockActual() < 10) {
//        JOptionPane.showMessageDialog(
//            this,
//            "El producto '" + i.getNombre() + "' tiene stock bajo (" + i.getStockActual() + ").",
//            "Alerta de Inventario",
//            JOptionPane.WARNING_MESSAGE
//        );
//    }
    }
    txtTotalInventario.setText(String.format("Stock total comprado: $ %.2f", totalInventario));
    txtStockDisponible.setText(String.format("Stock disponible físico: $ %.2f", totalRecibido));
}

   
  
    // Método para configurar el renderer
    private void configurarRenderer() {
    TablaInventario.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

            java.awt.Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            // Estado (columna 6)
            String estado = (String) table.getValueAt(row, 6); 
            if ("Cancelado".equalsIgnoreCase(estado)) {
                comp.setForeground(java.awt.Color.RED);
            } else {
                comp.setForeground(java.awt.Color.BLACK);
            }

            //  Stock bajo (columna 4)
            try {
                int stock = Integer.parseInt(table.getValueAt(row, 4).toString());
                if (stock < 10) {
                    // Resaltar toda la fila con fondo amarillo
                    comp.setBackground(java.awt.Color.YELLOW);
                    comp.setFont(comp.getFont().deriveFont(java.awt.Font.BOLD));
                } else {
                    // Restaurar fondo normal si no está seleccionado
                    if (!isSelected) {
                        comp.setBackground(java.awt.Color.WHITE);
                    }
                }
            } catch (NumberFormatException e) {
                // Ignorar si no es número
            }

            return comp;
        }
    });
}

    


    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtTotalInventario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInventario = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        txtStockDisponible = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Exportar CVS");

        jButton2.setText("Solo Alertas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Articulo", "Nombre", "Unidad", "Cantidad Comprada", "Stock Actual", "Costo Unitario", "Valor Inventario", "Estado"
            }
        ));
        TablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaInventario);
        if (TablaInventario.getColumnModel().getColumnCount() > 0) {
            TablaInventario.getColumnModel().getColumn(0).setPreferredWidth(60);
            TablaInventario.getColumnModel().getColumn(1).setPreferredWidth(60);
            TablaInventario.getColumnModel().getColumn(2).setPreferredWidth(60);
            TablaInventario.getColumnModel().getColumn(3).setPreferredWidth(60);
            TablaInventario.getColumnModel().getColumn(5).setPreferredWidth(60);
            TablaInventario.getColumnModel().getColumn(7).setPreferredWidth(60);
        }

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Productos en Existencia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 797, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTotalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStockDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SistemaPrincipal sis = new SistemaPrincipal();
        sis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaInventarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaInventarioMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //TODO and your handling code here:
                                           
    InventarioDAO dao = new InventarioDAO();
    List<Inventario> lista = dao.listar();
    DefaultTableModel modelo = (DefaultTableModel) TablaInventario.getModel();
    modelo.setRowCount(0);

    // Preguntar al usuario qué quiere ver
    String[] opciones = {"Cancelado", "Parcial"};
    String seleccion = (String) JOptionPane.showInputDialog(
            this,
            "¿Qué estado deseas mostrar?",
            "Filtrar Alertas",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
    );

    if (seleccion == null) {
        return; // usuario canceló
    }

    double totalValor = 0;
    int totalCantidad = 0;

    for (Inventario i : lista) {
        if (seleccion.equalsIgnoreCase(i.getEstado())) {
            modelo.addRow(new Object[]{
                i.getIdArticulo(),
                i.getNombre(),
                i.getUnidad(),
                i.getCantidadComprada(),
                i.getStockActual(),
                String.format("%.2f", i.getCostoUnitario()),
                String.format("%.2f", i.getValorInventario()),
                i.getEstado()
            });

            totalValor += i.getValorInventario();
            totalCantidad += i.getStockActual();
        }
    }

    // Mostrar resultados según selección
    if ("Cancelado".equalsIgnoreCase(seleccion)) {
        txtTotalInventario.setText(String.format("Total $ Cancelado: %.2f", totalValor));
        txtStockDisponible.setText(""); // vacío o puedes poner "N/A"
    } else if ("Parcial".equalsIgnoreCase(seleccion)) {
        txtTotalInventario.setText(String.format("Valor total: $ %.2f", totalValor));
        txtStockDisponible.setText("Cantidad total: " + totalCantidad);
    }

    if (modelo.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No hay artículos en estado '" + seleccion + "'.");
    }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaInventario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtStockDisponible;
    private javax.swing.JTextField txtTotalInventario;
    // End of variables declaration//GEN-END:variables
}

